# Tutorial

## Isogenies

Construct an isogeny from a generator of the kernel

In [1]:
E = EllipticCurve(GF(11), [1, 0])
g = E.gens()[0]
g.order()

12

In [2]:
kernel = 6*g
kernel

(0 : 0 : 1)

In [3]:
I = E.isogeny(kernel)
I

Isogeny of degree 2 from Elliptic Curve defined by y^2 = x^3 + x over Finite Field of size 11 to Elliptic Curve defined by y^2 = x^3 + 7*x over Finite Field of size 11

In [4]:
%display latex

In [5]:
I.rational_maps()

((x^2 + 1)/x, (x^2*y - y)/x^2)

In [6]:
F = I.codomain()
F

Elliptic Curve defined by y^2 = x^3 + 7*x over Finite Field of size 11

We observe that the image curve has the same number of points, but not the same group structure

In [7]:
F.abelian_group()

Additive abelian group isomorphic to Z/6 + Z/2 embedded in Abelian group of points on Elliptic Curve defined by y^2 = x^3 + 7*x over Finite Field of size 11

In [8]:
E.abelian_group()

Additive abelian group isomorphic to Z/12 embedded in Abelian group of points on Elliptic Curve defined by y^2 = x^3 + x over Finite Field of size 11

In [9]:
%display plain

The same example over the rationals

In [10]:
E = EllipticCurve([1,0])
E

Elliptic Curve defined by y^2 = x^3 + x over Rational Field

In [11]:
P = E.lift_x(0)
P

(0 : 0 : 1)

In [12]:
P.order()

2

In [13]:
J = E.isogeny(P)
F = J.codomain()
F

Elliptic Curve defined by y^2 = x^3 - 4*x over Rational Field

In (very) limited cases, Sage can compute the isogeny given the image curve and the degree

In [14]:
JJ = E.isogeny(None, codomain=F, degree=2)
J == JJ

True

## Complex multiplication

Sage capabilities around complex multiplications, and quadratic imaginary orders in particular, are a bit limited, but still useful.

In [15]:
E = EllipticCurve([1,0])
E

Elliptic Curve defined by y^2 = x^3 + x over Rational Field

Test whether a curve has complex multiplication

In [16]:
E.has_cm()

True

Get the "CM discriminant", i.e. the discriminant of the order $\mathcal{O}$ isomorphic to $\mathrm{End}(E)$

In [17]:
E.cm_discriminant()

-4

(ordinary) curves over finite fields and the Frobenius endomorphism

In [18]:
E = EllipticCurve(GF(101), [1,2])
E

Elliptic Curve defined by y^2 = x^3 + x + 2 over Finite Field of size 101

In [19]:
E.j_invariant()

4

In [20]:
E.is_ordinary()

True

In [21]:
E.is_supersingular()

False

In [22]:
chi = E.frobenius_polynomial()
chi

x^2 - 2*x + 101

In [23]:
chi.discriminant()

-400

In [24]:
E.trace_of_frobenius()

2

In [25]:
O = E.frobenius_order()
O

Order in Number Field in phi with defining polynomial x^2 - 2*x + 101

In [26]:
O.is_maximal()

False

In [27]:
O.discriminant()

-400

In [28]:
K = O.number_field()
K

Number Field in phi with defining polynomial x^2 - 2*x + 101

In [29]:
OK = K.maximal_order()
OK

Gaussian Integers in Number Field in phi with defining polynomial x^2 - 2*x + 101

In [30]:
OK.discriminant()

-4

In [31]:
K.class_number()

1

In [32]:
OK.class_number()

1

In [33]:
K.class_group()

Class group of order 1 of Number Field in phi with defining polynomial x^2 - 2*x + 101

In [34]:
O.class_number()

4

## Hilbert class polynomials

The Hilbert class polynomial $H(-D)$ is the polynomial with coefficients in $ℤ$ whose roots are the $j$-invariants with CM by (the order of discriminant) $-D$.

In [35]:
H = hilbert_class_polynomial(-400)
H

x^4 - 1938773508354872717845384224*x^3 + 12869286863161864184636279443710336*x^2 - 19075061455767889406477974994607212544*x + 87448873738295790450948276123544550117376

In [36]:
H.is_irreducible()

True

In [37]:
H.change_ring(GF(101)).factor()

(x + 7) * (x + 24) * (x + 64) * (x + 97)

# Exercises

### Exercise 1

Consider the curve

In [38]:
E = EllipticCurve(GF(127), [97, 46])

List all isogenies with kernel of size 43 (i.e., of degree 43) defined over $𝔽_{127}$.

We check the order of the curve. Necessarily $E(𝔽_{127}) \simeq ℤ/129ℤ$.

In [40]:
factor(E.order())

3 * 43

We take a random point $P$ of order 43 and construct the isogeny $E → E/〈P〉$.

In [41]:
ord = 1
while ord != 43:
    P = 3*E.random_element()
    ord = P.order()
    print(ord)
E.isogeny(P)

43


Isogeny of degree 43 from Elliptic Curve defined by y^2 = x^3 + 97*x + 46 over Finite Field of size 127 to Elliptic Curve defined by y^2 = x^3 + 38*x + 16 over Finite Field of size 127

There is at least one $𝔽_{127}$-rational isogeny of degree 43, however there may be more. Indeed, an isogeny is rational if and only if $π(\ker φ) = \ker φ$.

By studying the factorization of the division polynomial, we see it splits completely in $𝔽_{127^7}$. We move to the next question.

In [42]:
E.division_polynomial(43).factor()

(43) * (x + 5) * (x + 11) * (x + 13) * (x + 14) * (x + 16) * (x + 19) * (x + 28) * (x + 49) * (x + 56) * (x + 69) * (x + 72) * (x + 76) * (x + 81) * (x + 85) * (x + 92) * (x + 93) * (x + 95) * (x + 112) * (x + 113) * (x + 116) * (x + 125) * (x^7 + 46*x^5 + 110*x^4 + 27*x^3 + 12*x^2 + 41*x + 105) * (x^7 + 81*x^5 + 94*x^4 + 81*x^3 + 108*x^2 + 92*x + 6) * (x^7 + 123*x^5 + 36*x^4 + 62*x^3 + 57*x^2 + 96*x + 54) * (x^7 + 3*x^6 + 15*x^5 + 104*x^4 + 109*x^3 + 84*x^2 + 47*x + 82) * (x^7 + 3*x^6 + 67*x^5 + 44*x^4 + 81*x^3 + 71*x^2 + 60*x + 52) * (x^7 + 3*x^6 + 101*x^5 + 74*x^4 + 102*x^3 + 68*x^2 + 118*x + 5) * (x^7 + 5*x^6 + 35*x^5 + 46*x^4 + 49*x^3 + 80*x^2 + 70*x + 18) * (x^7 + 5*x^6 + 45*x^5 + 25*x^4 + 109*x^3 + 70*x^2 + 50*x + 41) * (x^7 + 5*x^6 + 95*x^5 + 126*x^4 + 118*x^3 + 11*x^2 + 79*x + 3) * (x^7 + 6*x^6 + 35*x^5 + 48*x^4 + 103*x^3 + 113*x^2 + 39*x + 64) * (x^7 + 7*x^6 + 41*x^5 + 29*x^4 + 23*x^3 + 123*x^2 + 116*x + 5) * (x^7 + 8*x^6 + 33*x^5 + 18*x^4 + 106*x^3 + 102*x^2 + 118*x + 90) * 

How many isogenies of degree 43 does the curve have over $𝔽_{127^7}$?

We verify that $E[43] ⊂ E(𝔽_{127^7})$

In [43]:
EE = E.change_ring(GF(127^7))
EE.order().factor()

3 * 43^2 * 2017 * 47627959

In [44]:
EE.abelian_group()

Additive abelian group isomorphic to Z/12392461536087 + Z/43 embedded in Abelian group of points on Elliptic Curve defined by y^2 = x^3 + 97*x + 46 over Finite Field in z7 of size 127^7

We take a basis of $E[43]$

In [45]:
P, Q = EE.gens()
P = (12392461536087 // 43) * P
P.order(), Q.order()

(43, 43)

For each of the cyclic subgroups $G ⊂ E[43]$, we print the $j$-invariant of $E/G$.

In [46]:
EE.isogeny(Q).codomain().j_invariant()

113*z7^6 + 28*z7^5 + 89*z7^4 + 15*z7^3 + 93*z7^2 + 2*z7 + 120

In [47]:
sorted([EE.isogeny(P + i*Q).codomain().j_invariant() for i in range(43)])

[70,
 70,
 44*z7^5 + 112*z7^4 + 21*z7^3 + 6*z7^2 + 53*z7 + 111,
 13*z7^6 + 9*z7^5 + 41*z7^4 + 71*z7^3 + 57*z7^2 + 23*z7 + 6,
 111*z7^6 + 95*z7^5 + 75*z7^4 + 85*z7^3 + 114*z7^2 + 38*z7 + 9,
 40*z7^6 + 21*z7^5 + 64*z7^4 + 40*z7^3 + 31*z7^2 + 51*z7 + 16,
 82*z7^6 + 2*z7^5 + 116*z7^4 + 2*z7^3 + 63*z7^2 + 80*z7 + 19,
 87*z7^6 + 25*z7^5 + 88*z7^4 + 21*z7^3 + 119*z7^2 + 29*z7 + 27,
 116*z7^6 + 83*z7^5 + 102*z7^4 + 21*z7^3 + 23*z7^2 + 90*z7 + 37,
 69*z7^6 + 14*z7^5 + 120*z7^4 + 32*z7^3 + 98*z7^2 + 109*z7 + 37,
 24*z7^6 + 29*z7^5 + 23*z7^4 + 83*z7^3 + 35*z7^2 + 111*z7 + 39,
 8*z7^6 + 37*z7^5 + 35*z7^4 + 123*z7^3 + 19*z7^2 + 80*z7 + 40,
 88*z7^6 + 18*z7^5 + 77*z7^4 + 16*z7^3 + 54*z7^2 + 8*z7 + 45,
 16*z7^6 + 126*z7^5 + 75*z7^4 + 26*z7^3 + 126*z7^2 + 14*z7 + 45,
 14*z7^6 + 117*z7^5 + 115*z7^4 + 20*z7^3 + 44*z7^2 + 42*z7 + 50,
 8*z7^6 + 36*z7^5 + 53*z7^4 + 44*z7^3 + 2*z7^2 + 25*z7 + 51,
 110*z7^6 + 22*z7^5 + 30*z7^4 + 104*z7^3 + 91*z7^2 + 88*z7 + 53,
 51*z7^6 + 46*z7^5 + 34*z7^4 + 86*z7^3 + 60*z7^

We find twice $j = 70 ∈ 𝔽_{127}$ in the list, indicating there are two distinct isogenies to this curve. It is not difficult to prove that these isogenies must be $𝔽_{127}$-rational, while clearly all other isogenies to curves defined over $𝔽_{127^7}$ cannot be. However there is a simpler command to ask Sage to compute all rational isogenies for us, which confirms what we just found.

In [48]:
E.isogenies_prime_degree(43)

[Isogeny of degree 43 from Elliptic Curve defined by y^2 = x^3 + 97*x + 46 over Finite Field of size 127 to Elliptic Curve defined by y^2 = x^3 + 38*x + 16 over Finite Field of size 127,
 Isogeny of degree 43 from Elliptic Curve defined by y^2 = x^3 + 97*x + 46 over Finite Field of size 127 to Elliptic Curve defined by y^2 = x^3 + 100*x + 8 over Finite Field of size 127]

We could have predicted this using more theory. The Frobenius endomorphism has two eigenvalues modulo 43.

In [49]:
E.frobenius_polynomial().change_ring(GF(43)).roots()

[(41, 1), (1, 1)]

$λ = 1$ corresponds to the subgroup of $𝔽_{127}$-rational points of order 43

In [50]:
E.isogeny(3*E.gens()[0])

Isogeny of degree 43 from Elliptic Curve defined by y^2 = x^3 + 97*x + 46 over Finite Field of size 127 to Elliptic Curve defined by y^2 = x^3 + 38*x + 16 over Finite Field of size 127

$λ = -2$ corresponds to a subgroup $G$ such that $π(P) = -2P$ for each $P ∈ G$. We know these points are defined over $𝔽_{127^7}$, we can find them by iterating over all points of order $43$ and testing the condition.

A trick to get one such point faster is to obeserve that $(π + 2)(π - 1)(P) = 0$ for every $P ∈ E[43]$, thus if $Q = (π - 1)(P)$ then $(π + 2)(Q) = 0$.

In [51]:
Q = EE.point([P[0]^127, P[1]^127])
Q = Q - P
EE.isogeny(Q)

Isogeny of degree 43 from Elliptic Curve defined by y^2 = x^3 + 97*x + 46 over Finite Field in z7 of size 127^7 to Elliptic Curve defined by y^2 = x^3 + 100*x + 8 over Finite Field in z7 of size 127^7

### Exercise 2

Give the list of all elliptic curves defined over $ℚ$ with complex multiplication

(may require checking [Wikipedia](https://en.wikipedia.org/wiki/Class_number_problem))

### Exercise 3

Find a prime $p$ and an elliptic curve $E/𝔽_p$ such that $\#E(𝔽_p) = 101$.

Hint: try to find a solution to $p+1-t = 101$, then compute the discriminant of the Frobenius and use complex multiplication theory.

Use the previously found curve to construct an isogeny of degree $101^{10}$

### Exercise 4

Let $ω ∈ ℂ$ be a cube root of unity, the ring $ℤ[ω]$ is also known as the Eisenstein integers. Determine all elliptic curves with complex multiplication by $ℤ[ω]$.

### Exercise 5

Prove that $-163$ is not a square modulo all odd primes $< 41$. 

Hint: Let $E/ℚ$ be an elliptic curve with complex multiplication by (an order of discriminant) $-D$. Its reduction modulo $p$ is ordinary if and only if $-D$ is a square modulo $p$.

### Exercise 6

Find an elliptic curve $E/𝔽_{1613}$ and two distinct isogenies of degree $2311$ from $E$

Note: the challenge here is to make the computation run in a couple of seconds...